name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ui

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          # https://github.com/actions/setup-node/issues/706
          cache-dependency-path: ui

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

  manifest-ids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r utils/requirements.txt

      - name: Ensure manifest.new.yml is up to date
        run: |
          set +e
          ./utils/remove_manifest_ids.py
          git diff --exit-code manifest.new.yml
          exitcode=$?
          if [ $exitcode -eq 1 ] ; then
            echo "manifest.new.yml is not up to date with manifest.yml"
            echo "please run ./utils/remove_manifest_ids.py"
            echo "(do not run prettier or any formatter on manifest.new.yml)"
          fi
          exit $exitcode
